name: Playwright CI

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: write   # нужно е, за да комитнем в main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Runs tests  HTML + Allure
      - name: Run Playwright tests
        run: npx playwright test --reporter=line,html,allure-playwright

      # Generate Allure HTML
      - name: Generate Allure HTML
        run: npx allure generate ./allure-results --clean -o ./allure-report

      # Copy Allure in /docs/allure-report за GitHub Pages
      - name: Prepare /docs for GitHub Pages
        run: |
          rm -rf docs/allure-report
          mkdir -p docs/allure-report
          cp -r allure-report/* docs/allure-report/
          # small index, which redirects to /allure-report/
          cat > docs/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=./allure-report/">
          <title>Redirecting…</title>
          HTML

      # Commit changes in main (only docs/**)
      - name: Commit Pages content
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update Allure report"
          branch: main
          file_pattern: docs/**

      #  Playwright HTML uploaded below as artifact
      - name: Upload Playwright HTML report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
          if-no-files-found: ignore
          retention-days: 7
