name: Playwright CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Runs test with HTML + Allure reports
      - name: Run Playwright tests
        run: npx playwright test --reporter=line,html,allure-playwright

      # Always upload Playwright HTML report (even on fail)
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
          if-no-files-found: ignore
          retention-days: 7

      # Check for allure-results existence
      - name: Check if Allure results exist
        id: allure_check
        shell: bash
        run: |
          if compgen -G "allure-results/*" > /dev/null; then
            echo "has_results=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_results=false" >> "$GITHUB_OUTPUT"
          fi

      # Java is required for 'allure generate'
      - name: Setup Java (for Allure)
        if: ${{ always() && steps.allure_check.outputs.has_results == 'true' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Generate Allure HTML (само ако има резултати)
      - name: Generate Allure HTML
        if: ${{ always() && steps.allure_check.outputs.has_results == 'true' }}
        run: npx allure generate ./allure-results --clean -o ./allure-report

      # Upload Allure HTML report as an artifact
      - name: Upload Allure HTML report
        if: ${{ always() && steps.allure_check.outputs.has_results == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: allure-report/
          if-no-files-found: ignore
          retention-days: 7
