name: Publish Playwright & Allure Reports

on:
  workflow_run:
    workflows: ["Playwright CI"]
    types: [completed]

permissions:
  contents: write  # нужно за push към gh-pages
  actions: read    # нужно за download от чужд run

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Allure HTML report
        uses: actions/download-artifact@v4
        with:
          name: allure-html-report          # ИМЕТО МУ В TEST JOB Е 'allure-html-report'
          path: ./site/allure
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Download Playwright HTML report
        uses: actions/download-artifact@v4
        with:
          name: playwright-html-report      # ИМЕТО МУ В TEST JOB Е 'playwright-html-report'
          path: ./site/playwright
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Create simple index.html with links
        run: |
          cat > ./site/index.html <<'HTML'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <title>Test Reports</title>
            <style>
              body { font-family: system-ui, sans-serif; padding: 2rem; line-height: 1.6; }
              a { display: block; font-size: 1.1rem; margin: .5rem 0; }
            </style>
          </head>
          <body>
            <h1>Test Reports</h1>
            <a href="playwright/index.html">▶ Playwright HTML report</a>
            <a href="allure/index.html">▶ Allure HTML report</a>
          </body>
          </html>
          HTML

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          commit_message: "docs(report): publish Playwright & Allure"
